### ISSUE TITLE
Dare I say... Non-semantic HTML?!? (EGAD!)

### ISSUE THREAD

**Issue by athanclark** [stubbornella/oocss#108]
Hi there. So I was pokin though your modules demo you have hosted on oocss.com, and I saw that in your modules you have `<b>` tags for defining the corners of the styles. Is that semantic? I heard that `<b>` and `<i>` were depreciated with HTML5, but don't quote me. Maybe a `<span>` would be more appropriate? Anyway, I thought you might want to make it mo' betta, so there's my suggestion.

Thank you so much for the presentation you gave on oocss. That was the most helpful thing I have seen for CSS ever. Incredible what you've done and what you are doing for everyone. God bless.
I really hope someone has bought you that "CSS is Awesome" shirt.

**Comment by csswizardry** [comment]
Hey there!

`b` and `i` have been redefined in HTML5 so they’re back in and totally above board :) Further to that, if the elements are empty (like empty `i` elements for spriting etc) then they don’t affect anything; they don’t pass their meaning on because there’s nothing to pass it on to. Using a `span` is also totally fine, but if the element you are using is for all intents and purposes a ‘freebie’ you might as well use the shortest!

Hope that helps!

Best,
H
